services:
  postgres:                      # service name, becomes the hostname on Docker network
    image: postgres:15           # use official Postgres image
    container_name: health-postgres
    restart: unless-stopped      # auto restart unless manually stopped
    ports:
      - "5433:5432"              # expose Postgres to host (localhost:5432)
    env_file: ../.env            # load env vars from root .env
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/

  metabase:
    image: metabase/metabase:latest
    container_name: health-metabase
    restart: unless-stopped
    ports:
      - "3000:3000"              # Metabase UI at http://localhost:3000
    env_file: ../.env
    depends_on:
      - postgres                 # wait for Postgres to be healthy
